<template>
  <n-h1>How to</n-h1>
  <!-- lorem ipsum -->
  <HelpStep stepNumber="1">
    If you're creating a new file, jump to step 2. To continue editing an existing file, click on "Load JSON" and select it. Remember: Once you’ve finished editing it, you must redownload it.
  </HelpStep>
  <HelpStep stepNumber="2">
    If you want to use a custom scheme for company identifiers generation, you can expand the “Company ID Settings” section and choose the desired ID generation method.
  </HelpStep>
  <HelpStep stepNumber="3">
    Fill out the following fields: Company Name, Company ID (if it is not generated automatically), Operation company (if applied), and (company) Type.
  </HelpStep>
  <HelpStep stepNumber="4">
    For every service evaluated, click on “Add a new service” and fill out the following fields: ID (you can leave the autogenerated suggestion), Service name, Service type, and Sub-type (if applied).
  </HelpStep>
  <HelpStep stepNumber="5">
    Repeat the previous step until all services have been added.
  </HelpStep>
  <HelpStep stepNumber="6">
    Next, click on "Create company," once created you can edit it or remove it from the list below.
  </HelpStep>
  <HelpStep stepNumber="7">
    Repeat steps from 3 to 6, until you’ve added all relevant companies.
  </HelpStep>
  <HelpStep stepNumber="8">
    Once you’ve added all relevant companies and services, you can download the configuration file by clicking on “Download JSON.” Save the file on your device.
  </HelpStep>
  <HelpStep stepNumber="9">
    You can continue the process by going to the “Workspace setup” section, to generate the spreadsheets.
  </HelpStep>
  <br />
  <help-meanings :items="vocabulary" />
</template>

<script setup lang="ts">
import HelpStep from '../components/HelpStep.vue';
import HelpMeanings from '../components/HelpMeanings.vue';
import type { VocabularyItem } from '@/entities/VocabularyItem';
import { NH1 } from 'naive-ui';

const vocabulary: Array<VocabularyItem> = [
  {
    name: 'Company name',
    description:
      'Name of the corporate group or main company to evaluate.',
    example: 'ACME Inc',
  },
  {
    name: 'Company id',
    description:
      'Internal unique identifier. This can be automatically generated or manually set up.',
  },
  {
    name: 'Operating company',
    description:
      'For internet platforms, leave this field blank because it does not apply. For telecommunication companies, leave it blank for telcos operating only at local level. If it’s a multinational company, add the name of the branch which operates locally here.',
  },
  {
    name: 'Type',
    description:
      'From the dropdown menu, select whether the company is an Internet platform or a Telecom company.',
  },
  {
    name: 'Services',
    description:
      'For each service evaluated, include its ID, name, type and subtype.',
  },
];
</script>
